# 공통 설정
spring:
    application:
        name: auth
    profiles:
        active: local # 기본 프로필 설정
    cloud:
        config:
            fail-fast: true
            retry:
                initial-interval: 1000
                max-interval: 2000
                max-attempts: 100

---
# local 환경 설정
spring:
    config:
        activate:
            on-profile: local
        import: optional:configserver:http://${CONFIG_LOCAL_HOST}:${CONFIG_LOCAL_PORT}
    cloud:
        config:
            profile: local
            label: main

---
# dev 환경 설정
spring:
    config:
        activate:
            on-profile: dev
        import: optional:configserver:http://${CONFIG_DEV_HOST}:${CONFIG_DEV_PORT}
    cloud:
        config:
            profile: dev
            label: main

---
# prod 환경 설정
spring:
    config:
        activate:
            on-profile: prod
        import: optional:configserver:http://${CONFIG_PROD_HOST}:${CONFIG_PROD_PORT}
    cloud:
        config:
            profile: prod
            label: main
