# 공통 설정
spring:
    application:
        name: auth
    profiles:
        active: local # 기본 프로필 설정
    cloud:
        config:
            fail-fast: true
            retry:
                initial-interval: 1000
                max-interval: 2000
                max-attempts: 100

session:
    service:
        url: ${SESSION_SERVICE_URL:http://localhost:8052}

---
# local 환경 설정
spring:
    config:
        activate:
            on-profile: local
        import: optional:configserver:http://${CONFIG_LOCAL_HOST:localhost}:${CONFIG_LOCAL_PORT:8058}
    cloud:
        config:
            profile: local
            label: main

---
# dev 환경 설정
spring:
    config:
        activate:
            on-profile: dev
        import: optional:configserver:http://${CONFIG_DEV_HOST:config-server}:${CONFIG_DEV_PORT:8058}
    cloud:
        config:
            profile: dev
            label: main

---
# prod 환경 설정
spring:
    config:
        activate:
            on-profile: prod
        import: optional:configserver:http://${CONFIG_PROD_HOST:config-server}:${CONFIG_PROD_PORT:8058}
    cloud:
        config:
            profile: prod
            label: main
logging:
    level:
        org.springframework.cloud: DEBUG
        org.springframework.security: DEBUG
        com.zerry.auth: DEBUG
